collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.718638
color:
  saturation: 0.7193649
  brandStrength: 0.2057949
  rhythmicContrast: 0.7161093
  brandColors:
    - '#FFFFFF'
    - '#1F1F1F'
    - '#036477'
    - '#777777'
    - '#FBC530'
  lightness: 0.3335178
layout_spectrum: 0.5035842
name: Comunic
