name: Comunic
favicon: null
layout_spectrum: 1
typography_spectrum: 0.718638
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Prova de la pàgina web
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#1F1F1F'
    - '#036477'
    - '#777777'
    - '#FBC530'
  brandStrength: 0.2057949
  lightness: 0.3335178
  saturation: 0.7193649
  rhythmicContrast: 0.7161093
purpose: []
